[package]
name = "repl-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "repl_rs"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.10.1"
eros = "0.1.0"
logos = "0.15.1"
num-bigint = "0.4.6"
num-traits = "0.2.19"
